# -*- coding: utf-8 -*-
"""تولید installer/files.nsi — لیست chunkبندی‌شده‌ی فایل‌ها برای نصب‌کننده‌ی NSIS.

خروجی هر chunk:
    SetOutPath ... / File ... (چند فایل در یک خط، بر اساس دایرکتوری)
    SendMessage $ProgressBar ${PBM_SETPOS} <pct> 0   (+ UpdateWindow)
    به‌روزرسانی متن وضعیت

اجرا در CI (روی Windows runner):
    python installer/gen_filelist.py --dist dist/CCTV_CMS --out installer/files.nsi
"""

import argparse
import os
from pathlib import Path

MAX_FILES_PER_LINE = 40


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dist", required=True, help="پوشه‌ی خروجی PyInstaller (مثل dist/CCTV_CMS)")
    ap.add_argument("--out", required=True)
    ap.add_argument("--chunks", type=int, default=14)
    args = ap.parse_args()

    dist = Path(args.dist)
    files = []
    for root, _dirs, names in os.walk(dist):
        for n in names:
            p = Path(root) / n
            rel = p.relative_to(dist).as_posix()
            files.append((rel, p.stat().st_size))
    files.sort(key=lambda x: x[0])
    if not files:
        raise SystemExit(f"no files found under {dist}")

    total = sum(s for _, s in files)
    target = max(total // args.chunks, 1)

    chunks, cur, cur_size = [], [], 0
    for rel, size in files:
        cur.append((rel, size))
        cur_size += size
        if cur_size >= target and len(chunks) < args.chunks - 1:
            chunks.append(cur)
            cur, cur_size = [], 0
    if cur:
        chunks.append(cur)

    n = len(chunks)
    L = []
    L.append("; === generated by installer/gen_filelist.py — do not edit by hand ===")
    L.append(f"; source: {dist} | files: {len(files)} | chunks: {n}")
    for i, chunk in enumerate(chunks):
        pct = int((i + 1) * 100 / n)
        L.append(f"; ---- chunk {i + 1}/{n} ----")
        bydir = {}
        for rel, _size in chunk:
            d = os.path.dirname(rel).replace("/", "\\")
            bydir.setdefault(d, []).append(rel.replace("/", "\\"))
        for d in sorted(bydir):
            outpath = "$INSTDIR" if not d else f"$INSTDIR\\{d}"
            L.append(f'SetOutPath "{outpath}"')
            names = bydir[d]
            for j in range(0, len(names), MAX_FILES_PER_LINE):
                quoted = " ".join(f'"${{DISTDIR}}\\CCTV_CMS\\{x}"' for x in names[j:j + MAX_FILES_PER_LINE])
                L.append(f"File {quoted}")
        L.append(f'SendMessage $ProgressBar ${{PBM_SETPOS}} {pct} 0')
        # نکته‌ی مهم: وقتی نخ UI داخل دستورهای File قفل است، UpdateWindow
        # به‌تنهایی نوار را نقاشی نمی‌کند (همین باگ «نوار لودینگ کار نمی‌کند»).
        # RedrawWindow با RDW_UPDATENOW نقاشی را هم‌گام و فوری انجام می‌دهد.
        L.append("System::Call 'user32::RedrawWindow(i $ProgressBar, i 0, i 0, i 0x181)'")
        L.append(f'${{NSD_SetText}} $StatusLabel "در حال کپی فایل‌ها… {pct}٪"')
        L.append("System::Call 'user32::RedrawWindow(i $StatusLabel, i 0, i 0, i 0x181)'")
        L.append("Sleep 30")
        L.append("")

    Path(args.out).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {args.out}: {len(files)} files in {n} chunks")


if __name__ == "__main__":
    main()
